# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-31 16:31
from __future__ import unicode_literals

from django.db import migrations, models
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('ISBN', isbn_field.fields.ISBNField(max_length=13, primary_key=True, serialize=False, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN')),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('author', models.CharField(max_length=256)),
            ],
        ),
    ]
