# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aritst_Name', models.CharField(max_length=200)),
                ('Song_Name', models.CharField(max_length=100)),
                ('Release_Year', models.DateTimeField(verbose_name='Year song was released')),
                ('Record_Label', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='MusicCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='favoritesong',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='musicapp.MusicCategory'),
        ),
    ]
